# Generated by Django 4.0.2 on 2022-02-25 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0005_comment_comment_user_saveuserpost_save_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_user',
        ),
        migrations.RemoveField(
            model_name='saveuserpost',
            name='save_user',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='post_user',
        ),
    ]
