# Generated by Django 4.0.2 on 2022-02-28 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0007_comment_comment_user_saveuserpost_save_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='userpostC',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='userpostC', to='home_app.userpost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saveuserpost',
            name='userpostS',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='userpostS', to='home_app.userpost'),
            preserve_default=False,
        ),
    ]
