# Generated by Django 4.0.2 on 2022-03-01 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home_app', '0008_comment_userpostc_saveuserpost_userposts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saveuserpost',
            name='updated',
        ),
        migrations.CreateModel(
            name='LikeUserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isLiked', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('like_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('userpostL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userpostL', to='home_app.userpost')),
            ],
        ),
    ]
